---
# roles/vagrant-aws-setup/tasks/main.yml

- name: get vagrant package
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    dest: /tmp/vagrant.deb
  vars:
  - vagrant_version: 2.2.5

- block:
  - name: install vagrant
    command: dpkg -i "/tmp/vagrant.deb"
  become: yes
# block end

- name: install vagrant-aws plugin
  command: vagrant plugin install vagrant-aws

- name: get vagrant aws dummy box
  command: vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
  register: awsbox
  failed_when: "'exists' not in awsbox.stderr"

- name: create Vagrant box
  template:
    src: Vagrantfile.j2
    dest: aws-demo/Vagrantfile
