---
# roles/vagrant-setup/tasks/main.yml

- block:
  - name: add oracle yum source for virtualbox
    # http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
    yum_repository:
      name: virtualbox
      description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
      baseurl: http://download.virtualbox.org/virtualbox/rpm/el/6/$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

  - name: install virtualbox prerequisites
    yum:
#      name: ['epel-release', 'gcc','dkms', 'make', 'qt', 'libgomp', 'patch', 'kernel-headers', 'kernel-devel', 'binutils', 'glibc-headers', 'glibc-devel', 'font-forge']
#      name: ['epel-release', 'gcc','dkms', 'make', 'libgomp', 'patch', 'kernel-headers', 'kernel-devel', 'binutils', 'glibc-headers', 'glibc-devel']
#      name:
#      - crypto-utils
#      - fuse-cryptofs
#      - m2crypto
#      - python-crypto
#      - gcc
#      - gcc-c++
      name:
      - dkms 
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
#      - kernel-pae-devel

  - name: install virtualbox
    yum:
      name: ['VirtualBox-{{ virtualbox_version }}']
      update_cache: yes
    vars:
    - virtualbox_version: 5.2
    # Use virtualbox 5.2 (v6 had issues being detected as a vagrant provider)

#  - name: get vagrant rpm from hashicorp
#    get_url:
#      url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
#      dest: "/tmp/vagrant_{{ vagrant_version }}.rpm"
#      checksum: sha256:https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_SHA256SUMS

  - name: install vagrant
    yum:
      name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
    vars:
    - vagrant_version: 2.2.5
  become: yes
# block end

# Manually rebuild virtualbox (if not detected as provider)
# sudo /sbin/vboxconfig
#
# May also need to install:
# linux-headers-amd64
# linux-headers-4.9.0-4-amd64
