- name: Test for local ssh
  command:
    cmd: timeout 1m ssh localhost "echo success"
  register: localssh_result

- block:
  - name: ensure ~/.ssh exists
    file:
      state: directory
      path: ~/.ssh
      mode: 0644

  - name: generate ssh key pair
    openssh_keypair:
      user: "{{ ansible_user }}"
      path: "~/.ssh/id_rsa"

  - name: add to authorized_keys
    authorized_key:
      user: "{{ ansible_user }}"
      path: "~/.ssh/id_rsa.pub"
  when: localssh_result is failed
#block end
