---
# roles/local-ssh/tasks/main.yml

- name: test for local ssh
  command:
    cmd: timeout 1m ssh localhost "echo success"
  register: localssh_result
  failed_when: false
  changed_when: localssh_result.rc != 0

- block:
  - name: ensure ~/.ssh exists
    file:
      state: directory
      path: ~/.ssh
      mode: 0744

  - name: generate ssh key pair
    openssh_keypair:
      owner: "{{ ansible_user }}"
      path: "~/.ssh/id_rsa"
      comment: "ansible-generated-localhost-key"
    register: local_sshkey

  - name: add to authorized_keys
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ local_sshkey.public_key }}"

  - name: create known_hosts (if not present)
    file:
      path: ~/.ssh/known_hosts
      state: touch

  - name: add host to known_hosts
    shell:
      cmd: "ssh-keyscan -H localhost >> ~/.ssh/known_hosts"

  when: localssh_result.rc != 0
#block end
